spring.jackson:
  deserialization:
    fail-on-unknown-properties: false
    read-date-timestamps-as-nanoseconds: false
  serialization:
    write-dates-as-timestamps: true
    write-date-timestamps-as-nanoseconds: false

features.static-path: /static/source-data.json
